server:
  port: 8083

spring:
  config:
    import: optional:nacos:application.yml
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: msh20040720
    url: jdbc:mysql://localhost:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8721
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-rules
            groupId: DEFAULT_GROUP
            rule-type: flow

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# Seata配置 - 暂时注释掉，待需要时恢复
# seata:
#   tx-service-group: my_test_tx_group
#   service:
#     vgroup-mapping:
#       my_test_tx_group: default
#     grouplist:
#       default: 127.0.0.1:8091
#   registry:
#     type: nacos
#     nacos:
#       server-addr: localhost:8848
#       namespace: public
#       group: SEATA_GROUP
#   config:
#     type: nacos
#     nacos:
#       server-addr: localhost:8848
#       namespace: public
#       group: SEATA_GROUP
#   enable-auto-data-source-proxy: true

# 日志配置
logging:
  level:
    com.example.order: debug 

management:
  endpoints:
    web:
      exposure:
        include: "*" 